swagger: "2.0"

info:
  title: RealMQ client api
  version: 0.0.0

paths: !includeMerged
  - routes/auth/tokens.yaml
  - routes/auth/tokens/{id}.yaml
  - routes/channels.yaml
  - routes/channels/{id}.yaml
  - routes/me/user.yaml
  - routes/subscriptions.yaml
  - routes/subscriptions/{id}.yaml
  - routes/users.yaml
  - routes/users/{id}.yaml
  - routes/version.yaml
tags:
  - name: Auth
    description: Manage authorization and authentication.
  - name: Channels
    description: Manage channels.
  - name: Users
    description: Manage users.
  - name: Subscriptions
    description: Manage user access on channels.
  - name: Me
    description: Manage resources represented by the authenticated client.
  - name: Info
    description: Information about the API.
parameters: !include openapi/parameters.yaml

definitions: !include openapi/definitions.yaml

securityDefinitions: !include openapi/security-definitions.yaml

security:
  - authTokenScheme: []
