swagger: "2.0"

info:
  title: RealMQ client api
  version: 0.0.0

paths: !includeMerged
  - routes/channels.yaml
  - routes/channels/{id}.yaml
  - routes/me/user.yaml
  - routes/subscriptions.yaml
  - routes/subscriptions/{id}.yaml
  - routes/users.yaml
  - routes/users/{id}.yaml
  - routes/version.yaml

parameters: !include openapi/parameters.yaml

definitions: !include openapi/definitions.yaml

securityDefinitions: !include openapi/security-definitions.yaml

security:
  - authTokenScheme: []
