swagger: "2.0"

info:
  title: RealMQ client api
  version: 0.0.0

paths:
  /version: !include routes/version.yaml

securityDefinitions: !include openapi/security-definitions.yaml

security:
  - authTokenScheme: []
