swagger: "2.0"

info:
  title: RealMQ client api
  version: 0.0.0
  description: |
    ## Getting Started

    * Get in touch with us to get an account set up. You can do that by sending an email to <a href="mailto:service@realmq.com">service@realmq.com</a>
    * We'll provide you with an `accessToken` with admin scope that allows you to create further users and access tokens.
    * Paste the `accessToken` into the access token input field in the header of the api browser.
    * There are two access groups (**scopes**). Every API endpoint has a description of what scopes are allowed to perform requests.
      - **admin** Full management capabilities, administration capabilities
      - **user** Restricted access

    ## API Resources

    * **Users**: A user may be a human, a bot, a sensor, a server etc. and is able to participate in channel communications.
    * **Channels**: A channel is a message gateway and broadcasts a message, data, event etc. to all its users.
    * **Subscriptions**: A subscription describes the access rights of users on channels.
    * **Auth Tokens**: A token is issued for one user and grants scope specific Rest- & Realtime API access rights.

    ## Custom Ids

    * In order to provide optimal integratability, you can work with custom ids on channels, users, subscriptions and auth-tokens.
    * When creating these resources, you can pass an `id` property to the payload.
    * You can then reference the resource by its custom id: eg. `GET /users/test-bot-1`.
    * Valid ids must match `^[\w-]+$` (**alpha-numeric**, **-**, **_**).
    * If you do not provide a custom id, a UUIDv4 will be generated by default.

    ## Error Responses

    | Status Code | Error Code | Error Message |
    | --- | --- | --- |
    | **400 - Bad Request** | `InvalidRequestSchema` | Request validation failed: Parameter (offset) is not a valid integer: INVALID_INPUT. |
    |                       | `AlreadySubscribed` | The subscription could not be created, since the given user is already subscribed to the channel. |
    |                       | `AuthTokenAlreadyExists` | The auth token could not be created, since a token with the same id already exists. |
    |                       | `ChannelAlreadyExists` | The channel could not be created, since a channel with the same id already exists.. |
    |                       | `InvalidAuthToken` | Patch cannot be applied, since the resulting auth token won't be valid. |
    |                       | `InvalidChannel` | Patch cannot be applied, since the resulting channel won't be valid. |
    |                       | `InvalidPatch` | The given payload is no valid JSON-Patch document. |
    |                       | `InvalidSubscription` | Patch cannot be applied, since the resulting subscription won't be valid. |
    |                       | `InvalidUser` | Patch cannot be applied, since the resulting user won't be valid. |
    |                       | `SubscriptionAlreadyExists` | The subscription could not be created, since a subscription with the same id already exists. |
    |                       | `UserAlreadyExists` | The user could not be created, since a user with the same id already exists. |
    | **401 - Unauthorized** | `InvalidAuthorization` | Missing or invalid authorization header. |
    | **403 - Forbidden** | `InsufficientPrivileges` | Insufficient rights to access or manipulate the requested resource. |
    | **404 - Not Found** | `EndpointNotFound` | The requested API endpoint does not exist. |
    |                     | `UnknownAuthToken` | The requested auth token does not exist. |
    |                     | `UnknownChannel` | The requested channel does not exist. |
    |                     | `UnknownSubscription` | The requested subscription does not exist. |
    |                     | `UnknownUser` | The requested user does not exist. |
    | **500 - Internal Server Error** | `InternalServerError` | Your request could not be processed. |
paths: !includeMerged
  - routes/auth/tokens.yaml
  - routes/auth/tokens/{id}.yaml
  - routes/channels.yaml
  - routes/channels/{id}.yaml
  - routes/channels/{channelId}/messages.yaml
  - routes/me/auth/token.yaml
  - routes/me/user.yaml
  - routes/subscriptions.yaml
  - routes/subscriptions/{id}.yaml
  - routes/users.yaml
  - routes/users/{id}.yaml
  - routes/version.yaml
tags:
  - name: Auth
    description: Manage authorization and authentication.
  - name: Channels
    description: Manage channels.
  - name: Users
    description: Manage users.
  - name: Subscriptions
    description: Manage user access on channels.
  - name: Me
    description: Manage resources represented by the authenticated client.
  - name: Info
    description: Information about the API.
parameters: !include openapi/parameters.yaml

definitions: !include openapi/definitions.yaml

securityDefinitions: !include openapi/security-definitions.yaml

security:
  - authTokenScheme: []
