version: '3'

services:
  dispatcher:
    image: realmq/realmq-dispatcher
    volumes:
      - certificates-volume:/data/certificates
    ports:
      - ${PORT_HTTP:-80}:80
      - ${PORT_HTTPS:-443}:443
    environment:
      - TLD=${DOMAIN:-realmq.local}
      - TLS_CERT=/data/certificates/${DOMAIN:-realmq.local}.crt.pem
      - TLS_CERT_KEY=/data/certificates/${DOMAIN:-realmq.local}.key.pem
      - TLS_CERT_ROOT=/data/certificates/root.crt.pem
    depends_on:
      - broker
      - certificates
      - platform

  platform:
    build:
      context: .
    command: npm run start-debug
    restart: always
    ports:
      - ${PORT:-8080}:${PORT:-8080}
      - 9229:9229
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=${PORT:-8080}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - BROKER_HOST=broker
      - BROKER_USERNAME=adapter
      - BROKER_PASSWORD=adapter
      - API_BROKER_KEY=broker-key
      - API_ADMIN_KEY=${API_ADMIN_KEY}
    depends_on:
      - broker
      - database

  database:
    image: bitnami/mongodb
    volumes:
      - database-volume:/bitnami
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=realmq
      - MONGODB_PASSWORD=realmq
      - MONGODB_DATABASE=realmq

  broker:
    image: realmq/realmq-broker
    ports:
      - 1883:1883
    environment:
      - HOST=0.0.0.0
      - ADAPTER_KEY=broker-key
      - ADAPTER_HOST=platform
      - ADAPTER_PORT=${PORT:-8080}
      - CREDENTIALS=adapter:adapter

  certificates:
    image: realmq/dev-ca
    volumes:
      - certificates-volume:/data/certificates
    environment:
      - DOMAIN=${DOMAIN:-realmq.local}
      - SAN=api.${DOMAIN:-realmq.local} rtm.${DOMAIN:-realmq.local}
volumes:
  database-volume:
  certificates-volume:

